<template>
    <div class="widget Label" data-version="2" id="Label1">
        <div class="widget-title">
            <h3 class="title">Tags</h3>
        </div>
        <div class="widget-content cloud-label">
            <ul>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Beauty?&amp;max-results=5"
                    >
                        Beauty
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Business?&amp;max-results=5"
                    >
                        Business
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Fashion?&amp;max-results=5"
                    >
                        Fashion
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Food?&amp;max-results=5"
                    >
                        Food
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Learn?&amp;max-results=5"
                    >
                        Learn
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Music?&amp;max-results=5"
                    >
                        Music
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Nature?&amp;max-results=5"
                    >
                        Nature
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/People?&amp;max-results=5"
                    >
                        People
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Photography?&amp;max-results=5"
                    >
                        Photography
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Sports?&amp;max-results=5"
                    >
                        Sports
                    </a>
                </li>
                <li>
                    <a
                        class="label-name"
                        href="https://wavy-way2themes.blogspot.com/search/label/Technology?&amp;max-results=5"
                    >
                        Technology
                    </a>
                </li>
            </ul>
        </div>
    </div>
</template>
<script setup>

</script>